# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            ytysj
tagline:          'blog'
description:      'My personal blog.'
url:              http://ytysj.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           ytysj
  url:            http://weibo.com/3493499301/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         weibo
    url:          http://weibo.com/3493499301/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
    desc:         Follow me on weibo

  - icon:         github
    url:          https://github.com/ytysj
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          
    desc:         

  - icon:         feed
    url:          
    desc:         

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         ytysj
  url:            http://ytysj.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
